2.5.3 update
optimacros/scripts_documentation pull request #21
Opened 2022-11-03 10:36 UTC by iMoonGoose

https://rucom.optimacros.com/topic/18522/отвалилась-аутентификация-по-domain-username-для-mssql/14

2022-11-03 16:35 UTC, m-golovkina requested changes

2022-11-03 16:35 UTC, m-golovkina commented on API/relationalDB.md
> +Описание актуально для версии `2.5.3`
Меня прям смущает эта строка. 
Во первых я сразу задаюсь вопросом - а версия чего? Хотя знаю что версия воркспейса ))) Поэтому стоит написать "Описание актуально для версии воркспейса `2.5.3`".

Во вторых я задумываюсь: 
а это все описание ниже актуально для версии 2.5.3 ? и раньше метод setDriver() был, а какое тогда раньше было актуальное описание.

короче может убрать это? или приписать сюда -> `DBLIB` **не позволяет** использовать `setScrollType` (что нужно для работы запросов в `WITH`, `DECLARE` и т.д.), но **позволяет** использовать доменную аутентификацию `DOMAIN\username` и `username@domain.zone` (актуально начиная с версии воркспейса `2.5.3`).

2022-11-03 16:35 UTC, m-golovkina commented on API/relationalDB.md
> +Описание актуально для версии `2.5.3`
Тоже самое что писала выше. Здесь мне кажется можно удалить.

2022-11-04 08:33 UTC, iMoonGoose commented on API/relationalDB.md
> +Описание актуально для версии `2.5.3`
1. У API скриптов всегда одна версия = версия воркспейса, потому что они крутятся на МВ, тут не может быть других трактовок.
2. Описание раньше можно посмотреть через историю коммитов. Правильно, конечно, чтобы версии описания скриптов всегда была синхронизирована с мастером МВ. Можно даже через релизы это делать. Но у нас постоянно отстаёт :( Давай я уберу и будем просто релиз делать с версией = версии воркспейса. Тогда по истории релизов можно будет всегда знать

2022-11-04 08:43 UTC, m-golovkina approved these changes

2022-11-04 08:43 UTC, merged