18845 Variables interface
optimacros/scripts_documentation pull request #30
Opened 2023-01-19 13:35 UTC by svowl

18845 EPIC Внедрение переменных (Variables) для работы скриптов и секретов
https://rucom.optimacros.com/topic/18845/

2023-01-20 09:13 UTC, iMoonGoose requested changes
Еще нужно обновить [scripts.om.d.ts](https://github.com/optimacros/scripts_documentation/blob/main/API/scripts.om.d.ts)

2023-01-20 09:13 UTC, iMoonGoose commented on API/variables.md
> +Интерфейс для доступа к переменным, заданным в системном мультикубе `Variables`.
Добавить, что этот МК и интерфейс к нему позволяют получать доступ к содержимому ячеек из скриптов, обходя любые настройки доступа

2023-01-20 09:13 UTC, iMoonGoose commented on API/variables.md
> +Интерфейс, предоставляющий методы для работы с переменной, полученной из системного мультикубе `Variables`.
мультикуба

2023-01-20 09:13 UTC, iMoonGoose commented on API/variables.md
> +Возвращает `true`, если значение переменной - объект EntityInfo и false в противном случае.
- объект EntityInfo, и `false` в

2023-01-20 11:23 UTC, svowl commented on API/variables.md
> +Интерфейс для доступа к переменным, заданным в системном мультикубе `Variables`.
добавил

2023-01-20 11:23 UTC, svowl commented on API/variables.md
> +Интерфейс, предоставляющий методы для работы с переменной, полученной из системного мультикубе `Variables`.
поправил

2023-01-20 11:23 UTC, svowl commented on API/variables.md
> +Возвращает `true`, если значение переменной - объект EntityInfo и false в противном случае.
поправил

2023-01-23 09:17 UTC, iMoonGoose requested changes
![image](https://user-images.githubusercontent.com/62833016/214003604-306270c4-1c25-46fb-9eb0-6c65088c3a93.png)

2023-01-23 09:40 UTC, svowl commented
> ![image](https://user-images.githubusercontent.com/62833016/214003604-306270c4-1c25-46fb-9eb0-6c65088c3a93.png)

сорри, не увидел этот коммент (
добавил

2023-01-24 07:05 UTC, merged