Model lock corrections
optimacros/scripts_documentation pull request #32
Opened 2023-01-20 14:41 UTC by qx87

2023-01-24 07:14 UTC, iMoonGoose requested changes
![image](https://user-images.githubusercontent.com/62833016/214231853-e9dbaacb-286b-46fa-9258-ff3ceff0175b.png)
Надо поправить заодно, что выбор режима в модалке скриптов а) устанавливает стартовый максимальный режим блокировки (скрипт может его изменить изнутри кодом), б) в режиме `Shared` и `Custom` разные скрипты могут работать параллельно

2023-01-24 07:14 UTC, iMoonGoose commented on advancedFeatues/modelLock.md
> +Optimacros предусматривает три уровня блокировки модели: `shared lock`, `unique lock` и `complete lock`, которые управляются функциями интерфейса [`ModelInfo`](../API/common.md#model-info).
Только 2 первые, `complete lock` нельззя управлять

2023-01-24 15:11 UTC, qx87 commented on advancedFeatues/modelLock.md
> +Optimacros предусматривает три уровня блокировки модели: `shared lock`, `unique lock` и `complete lock`, которые управляются функциями интерфейса [`ModelInfo`](../API/common.md#model-info).
Исправил

2023-01-26 06:46 UTC, iMoonGoose approved these changes

2023-01-26 06:46 UTC, merged