24704 oracle import
optimacros/scripts_documentation pull request #33
Opened 2023-03-06 14:36 UTC by orlov89

https://rucom.optimacros.com/topic/24704

2023-03-07 11:31 UTC, iMoonGoose requested changes
Нужно также обновить содержимое `scripts.om.d.ts`

2023-03-07 11:31 UTC, iMoonGoose commented on API/relationalDB.md
> +    loadImportBuilder(): OracleImportBuilder;
Здесь везде табы, нужно так и форматировать табами

2023-03-07 11:31 UTC, iMoonGoose commented on API/relationalDB.md
> +Устанавливает таблицу, из которой будет производиться импорт.
В которую будет производиться импорт

2023-03-07 11:31 UTC, iMoonGoose commented on API/relationalDB.md
> +Параметр определяющий будет ли импорт осуществляться ковенциональным способом (с помощью Insert запросов, значение `false`) или напрямую в файлы базы данных(значение `true`); Второй способ обычно нам
1. Запятые и пробелы
2. осуществляться с помощью Insert запросов (значение `false`)
3. `Опция` с заглавной

2023-03-07 11:31 UTC, iMoonGoose commented on API/relationalDB.md
> +Устанавливает разделитель полей. По умолчанию: `;`.
После `По умолчанию` не нужно никаких знаков препинания и так везде

2023-03-07 11:31 UTC, iMoonGoose commented on API/relationalDB.md
> +Задаёт порядок столбцов таблицы, в которые будут записываться данные из файла CSV; [`опция`](https://docs.oracle.com/en/database/oracle/oracle-database/19/sutil/oracle-sql-loader-control-file-content
Какая опция? Раз упоминается, нужно написать. И так везде

2023-03-07 11:31 UTC, iMoonGoose commented on API/relationalDB.md
> +Дает возможность включать параллельный импорт при включенном флаге `Direct`, см. метод `setDirect`. [`опция`](https://docs.oracle.com/cd/A57673_01/DOC/server/doc/SUT73/ch8.htm#ld%20dir%20parallel) *s
1. Что такое параллельный импорт парой слов? По ссылке стена текста
2. `Опция` с заглавной

2023-03-07 11:31 UTC, iMoonGoose commented on API/relationalDB.md
> +Если импорт завершён без ошибок, возвращает объект вида `{"skipped": 0}`, содержащий информацию о пропущенных строках.
Нужно описание объекта. Марина подсказывает, что там не `skipped`, а `ignored` к тому же

2023-03-07 11:31 UTC, iMoonGoose commented on API/relationalDB.md
> +    getStats(): object
Точка с запятой пропущена

2023-03-10 06:58 UTC, orlov89 commented on API/relationalDB.md
> +Дает возможность включать параллельный импорт при включенном флаге `Direct`, см. метод `setDirect`. [`опция`](https://docs.oracle.com/cd/A57673_01/DOC/server/doc/SUT73/ch8.htm#ld%20dir%20parallel) *s
После повторного чтения документации я вдруг понял, что он не будет работать в текущей реализации(точнее если его включить - импорт будет работать точно так же как если выключить). Удалил метод.

2023-03-10 10:19 UTC, iMoonGoose reviewed
1. Желательно отвечать по каждому комментарию по ревью
2. Я поправил запятые, пробелы
3. Я удалил из `scripts.om.d.ts` `setParallel()`

2023-03-10 10:19 UTC, iMoonGoose commented on API/relationalDB.md
> +Возвращает сформированную команду на вызов `sqlldr`, которая была выполнена в момент вызова [`OracleImportBuilder.import()`](#oracle-import-builder.import). Параметры будут сохранены в конфигурационн
1. К этому моменту импорт уже закончился, почему `будут сохранены в конфигурационном файле`
2. Методы `getConfig()` и `setConfig()` не описаны

2023-03-10 10:19 UTC, iMoonGoose commented on API/relationalDB.md
> +Параметр, определяющий, будет ли импорт осуществляться с помощью `INSERT`-запросов (значение `false`) или напрямую в файлы базы данных (значение `true`). Второй способ обычно намного быстрее. [`Опция
Какая опция? По ссылке стена текста

2023-03-10 10:19 UTC, iMoonGoose commented on API/relationalDB.md
> +Параметр, определяющий, будет ли импорт осуществляться с помощью `INSERT`-запросов (значение `false`) или напрямую в файлы базы данных (значение `true`). Второй способ обычно намного быстрее. [Опция]
Какая опция? По ссылке стена текста

2023-03-12 08:24 UTC, orlov89 commented on API/relationalDB.md
> +Возвращает сформированную команду на вызов `sqlldr`, которая была выполнена в момент вызова [`OracleImportBuilder.import()`](#oracle-import-builder.import). Параметры будут сохранены в конфигурационн
1. по сути этот метод вообще не нужны, т.к. комада содержит пути к уже удаленным файлам. Раньше она использовалась для подсчета пропущенных строк, сейчас же никакой смысловой нагрузки она не несет. Удалил метод `getCommand() `из `OracleImportResult`
2. `getConfig` поэтому и не описан в интерфейсе, потому что не используются при импорте oracle
3. `setConfig` не существует в `OracleImportResult` и не используется в `OracleImportBuilder`, поэтому не описан в интерфейсе

2023-03-12 08:26 UTC, orlov89 commented on API/relationalDB.md
> +Если импорт завершён без ошибок, возвращает объект вида `{"skipped": 0}`, содержащий информацию о пропущенных строках.
спасибо, поправил на `ignored`. Про описание не понятно - оно сейчас точно такое же как и у mysql getStats

2023-03-12 08:27 UTC, orlov89 commented on API/relationalDB.md
> +    getStats(): object
добавил, спасибо

2023-03-12 08:27 UTC, orlov89 commented on API/relationalDB.md
> +Устанавливает разделитель полей. По умолчанию: `;`.
поправил

2023-03-12 08:28 UTC, orlov89 commented on API/relationalDB.md
> +Параметр определяющий будет ли импорт осуществляться ковенциональным способом (с помощью Insert запросов, значение `false`) или напрямую в файлы базы данных(значение `true`); Второй способ обычно нам
поправил

2023-03-12 08:28 UTC, orlov89 commented on API/relationalDB.md
> +Устанавливает таблицу, из которой будет производиться импорт.
поправил

2023-03-12 08:28 UTC, orlov89 commented on API/relationalDB.md
> +    loadImportBuilder(): OracleImportBuilder;
поменял

2023-03-12 08:34 UTC, orlov89 commented on API/relationalDB.md
> +Параметр, определяющий, будет ли импорт осуществляться с помощью `INSERT`-запросов (значение `false`) или напрямую в файлы базы данных (значение `true`). Второй способ обычно намного быстрее. [`Опция
добавил пример опции. Поменял ссылку на более точное место, но не понял замечание про стену текста. Я не могу править структурирование документации внешнего сайта.

2023-03-12 08:35 UTC, orlov89 commented on API/relationalDB.md
> +Параметр, определяющий, будет ли импорт осуществляться с помощью `INSERT`-запросов (значение `false`) или напрямую в файлы базы данных (значение `true`). Второй способ обычно намного быстрее. [Опция]
ответил выше

2023-03-13 06:29 UTC, iMoonGoose approved these changes

2023-03-13 09:58 UTC, iMoonGoose approved these changes

2023-03-16 08:52 UTC, merged