TOPIC-25336: update mssql doc
optimacros/scripts_documentation pull request #34
Opened 2023-03-07 07:38 UTC by SarasovMatvey

https://rucom.optimacros.com/topic/25336/обновить-описание-интерфейса-microsoftsqlconnectorbuilder

2023-03-07 10:33 UTC, iMoonGoose requested changes
Нужно также обновить `scripts.om.d.ts`

2023-03-07 10:33 UTC, iMoonGoose commented on API/relationalDB.md
> +	setRequestTimeout(timeout: number): MicrosoftSqlConnectorBuilder;
Лучше переместить перед `loadBulkCopyBuilder(): SqlBulkCopyBuilder;`. Красивее :) Ну и чтобы всё, возвращающее `MicrosoftSqlConnectorBuilder`, шло подряд

2023-03-07 10:33 UTC, iMoonGoose commented on API/relationalDB.md
> +Устанавливает таймаут запроса в секундах. По умолчанию - таймаут отсутствует. Отрицательные значения не допускаются. Фактически устанавливает значение для аттрибута SQLSRV_ATTR_QUERY_TIMEOUT (https:/
1. По ссылке можно узнать, что число должно быть целым, стоит это тут написать
2. По ссылке можно узнать, что `0 = нет таймаута`. Какое поведение по умолчанию? Это `0`, как написано по ссылке, или какой-то стандартный таймаут? В темах, что я скидывал, Коля писал, что без указания у нас было 30 сек
3. Будет работать с любыми драйверами соединения? Или только `SQLSRV`?
4. SQLSRV_ATTR_QUERY_TIMEOUT поместить в обратные кавычки: `SQLSRV_ATTR_QUERY_TIMEOUT`
5. Скрыть ссылку за надпись вроде "Документация на сайте Microsoft"
6. Не нужен дефис (тире) после "По умолчанию"

2023-03-09 08:38 UTC, SarasovMatvey commented on API/relationalDB.md
> +Устанавливает таймаут запроса в секундах. По умолчанию - таймаут отсутствует. Отрицательные значения не допускаются. Фактически устанавливает значение для аттрибута SQLSRV_ATTR_QUERY_TIMEOUT (https:/
1. Указал.
2. Уточнил у Коли - да 30 секунд по умолчанию.
3. Да точно, не заметил. Функция работает с любыми драйверами - sqlsrv, odbc, dblib. Соответственно конкретизацию подкапотной работы при sqlsrv - убрал.
4. -
5. -
6. Убрал.

2023-03-09 09:03 UTC, iMoonGoose requested changes
![image](https://user-images.githubusercontent.com/62833016/223972619-fa30305c-76e2-4e77-aa2e-78cf400374e5.png)

2023-03-09 09:03 UTC, iMoonGoose commented on API/relationalDB.md
> +Устанавливает таймаут запроса в секундах. По умолчанию таймаут равен 30 секундам. Отрицательные и дробные значения не допускаются.
А зачем ссылку-то на документацию убрал? :) Скрыть - просто чтобы ссылка текстом не лежала, а красивой гиперссылкой была

2023-03-09 09:03 UTC, iMoonGoose commented on API/relationalDB.md
> +Устанавливает таймаут запроса в секундах. По умолчанию таймаут равен 30 секундам. Отрицательные и дробные значения не допускаются.
Ну и указать, что 0 = бесконечность

2023-03-09 09:05 UTC, iMoonGoose commented on API/relationalDB.md
> +Устанавливает таймаут запроса в секундах. По умолчанию таймаут равен 30 секундам. Отрицательные и дробные значения не допускаются.
![image](https://user-images.githubusercontent.com/62833016/223973129-e3c4eb28-edbc-44eb-b9f0-6866b36b1bb8.png)
Посместить в том же порядке, что и в описании интерфейса, пожалуйста

2023-03-16 08:57 UTC, merged