topic-19036 scripts promise
optimacros/scripts_documentation pull request #40
Opened 2023-04-12 08:19 UTC by MelkeeyD

https://rucom.optimacros.com/topic/19036/система-запуска-скриптов-по-расписанию-2-0

2023-07-25 16:42 UTC, m-golovkina requested changes

2023-07-25 16:42 UTC, m-golovkina commented on API/scriptChains.md
> +Устанавливает ограничение памяти. Работает аналогично ограничению памяти, выставляемому каждому скрипту в списке скриптов модели.
я бы еще добавила `... в списке скриптов модели на вкладке Макросы -> Скрипты`

2023-07-25 16:42 UTC, m-golovkina commented on API/scriptChains.md
> +Устанавливает ограничение времени. Работает аналогично ограничению времени выполнения, выставляемому каждому скрипту в списке скриптов модели.
И тут тоже `... в списке скриптов модели на вкладке Макросы -> Скрипты`

2023-07-25 16:42 UTC, m-golovkina commented on API/scriptChains.md
> +Запускает скрипт с помощью асинхронного механизма выполнения. Вызов метода породит задачу, которая не будет дожидаться завершения текущей задачи, а будет выполняться сразу. На данный момент существуе
Нужно перефразировать, то есть убрать одно слово `учитывать` -> Также **стоит учитывать**, что т.к. ..., то **нужно учитывать** ...

2023-07-25 16:42 UTC, m-golovkina commented on API/scriptChains.md
> +Работает так же, как и [`ResultMacrosAction`](#result-macros-action). [`buttonInfo()`](#result-macros-action.button-info).
Я думаю тут как раз пробел не нужен.

2023-07-25 16:42 UTC, m-golovkina commented on API/scriptChains.md
> +Возвращает описание задачи, установленное методом `setTaskDescription()`.
добавить якорь - ссылку на метод `setTaskDescription()`

2023-07-25 16:42 UTC, m-golovkina commented on API/scriptChains.md
> +Возвращает интерфейс [`EnvironmentInfo`](#environment-info) для чтения [`переменных окружения`](https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_%D1%81%D1%80
Тут мне не очень понятно. Это доступ к переменным окружения, которые были переданы скрипту при его запуске? А сам дочерний скрипт может что-то кроме своего лога передать родительскому скрипту?

2023-07-26 08:23 UTC, iMoonGoose commented on API/scriptChains.md
> +Устанавливает ограничение памяти. Работает аналогично ограничению памяти, выставляемому каждому скрипту в списке скриптов модели.
Done

2023-07-26 08:23 UTC, iMoonGoose commented on API/scriptChains.md
> +Устанавливает ограничение времени. Работает аналогично ограничению времени выполнения, выставляемому каждому скрипту в списке скриптов модели.
Done

2023-07-26 08:23 UTC, iMoonGoose commented on API/scriptChains.md
> +	*/
Done

2023-07-26 08:23 UTC, iMoonGoose commented on API/scriptChains.md
> +Запускает скрипт с помощью асинхронного механизма выполнения. Вызов метода породит задачу, которая не будет дожидаться завершения текущей задачи, а будет выполняться сразу. На данный момент существуе
Done

2023-07-26 08:23 UTC, iMoonGoose commented on API/scriptChains.md
> +Работает так же, как и [`ResultMacrosAction`](#result-macros-action). [`buttonInfo()`](#result-macros-action.button-info).
Done

2023-07-26 08:23 UTC, iMoonGoose commented on API/scriptChains.md
> +Возвращает описание задачи, установленное методом `setTaskDescription()`.
Done

2023-07-26 08:26 UTC, iMoonGoose commented on API/scriptChains.md
> +Возвращает интерфейс [`EnvironmentInfo`](#environment-info) для чтения [`переменных окружения`](https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_%D1%81%D1%80
Это интерфейс результата работы скрипта, соответственно переменные окружения этого скрипта, как они там считаются внутри ОМ (видимо, объект в базе монго). Дочерний скрипт не имеет связи с родительским. Родительский скрипт может получить информацию из монго базы о дочернем

2023-07-26 12:38 UTC, m-golovkina approved these changes

2023-07-26 13:22 UTC, merged