TOPIC-20858 Script import into time and version lists
optimacros/scripts_documentation pull request #49
Opened 2023-05-30 03:56 UTC by Toxin4ick

https://rucom.optimacros.com/topic/20858/реализовать-импорт-в-справочники-времени-и-версий

2023-06-14 14:15 UTC, m-golovkina requested changes

2023-06-20 06:05 UTC, Toxin4ick commented on API/dimensions.md
> +Возвращает ссылку на интерфейс импорта [`TimePeriodImporter`](./exportImport.md#timePeriod-importer).
+

2023-06-20 06:05 UTC, Toxin4ick commented on API/dimensions.md
> +Возвращает ссылку на [`ElementsCreator`](./elementsManipulator.md#elements-creator) для добавления элементов.
+

2023-06-20 06:05 UTC, Toxin4ick commented on API/dimensions.md
> +	storageImporter(): StorageImporter;
+

2023-06-20 06:05 UTC, Toxin4ick commented on API/dimensions.md
> +Возвращает интерфейс [`storageImporter`](./exportImport.md#storage-importer) для быстрого импорта данных в мультикуб.
+

2023-06-20 06:06 UTC, Toxin4ick commented on API/dimensions.md
> +Возвращает ссылку на [`ElementsCreator`](./elementsManipulator.md#elements-creator) для добавления элементов.
+

2023-06-20 06:06 UTC, Toxin4ick commented on API/dimensions.md
> +Возвращает ссылку на [`ElementsCreator`](./elementsManipulator.md#elements-creator) для добавления элементов.
+

2023-06-20 06:09 UTC, Toxin4ick commented on API/dimensions.md
> +Возвращает ссылку на интерфейс импорта [`VersionsImporter`](./exportImport.md#versions-importer).
+

2023-06-20 06:10 UTC, Toxin4ick commented on API/dimensions.md
> +Возвращает ссылку на [`ElementsCreator`](./elementsManipulator.md#elements-creator) для добавления элементов.
+

2023-06-20 06:10 UTC, Toxin4ick commented on API/dimensions.md
> +importer(): VersionsImporter
+

2023-06-20 06:10 UTC, Toxin4ick commented on API/dimensions.md
> +Возвращает ссылку на [`ElementsCreator`](./elementsManipulator.md#elements-creator) для добавления элементов.
+

2023-06-20 06:12 UTC, Toxin4ick commented on API/views.md
> +Возвращает ссылку на [`MulticubeTab`](#multicube-tab) куба `name`. Если такой мультикуб отсутствует, бросает исключение. В интерфейсе Optimacros аналогично открытию вкладки мультикуба `name`.
+

2023-06-20 06:13 UTC, Toxin4ick commented on API/views.md
+

2023-06-20 06:20 UTC, Toxin4ick commented on API/scripts.om.d.ts
>  export interface ListChildTab extends Tab {
Да, он уже не используется. Убрал.

2023-06-21 16:32 UTC, m-golovkina approved these changes

2023-06-30 09:15 UTC, merged