[+] Documentation for 'EnterpriseLicenseManager' API #23337
optimacros/scripts_documentation pull request #54
Opened 2023-06-21 12:04 UTC by MrSheriff

2023-06-28 11:00 UTC, qx87 requested changes

2023-06-29 05:37 UTC, iMoonGoose commented on API/common.md
> +interface ModelInfo {
Done

2023-06-29 05:39 UTC, iMoonGoose commented on API/common.md
> +Если на воркспейсе в панели администратора установлена лицензия, соответствующая зашитим в дистрибутив паролю и ключу, возвращает `true`. В противном случае возвращает `false`.
Давай такие вещи править сразу. Вот я сейчас в упор не вижу, где опечатка, аты в коментарии не отметил какая. Писать коммент "Опечатка" дольше, чем её править

2023-06-29 05:45 UTC, iMoonGoose commented on API/common.md
> +Создаёт ключ на основе пароля, которым можно в дальнейшем подписать лицензию. Повторный вызов приводит к разным результатам.
Поправил

2023-06-29 05:46 UTC, iMoonGoose commented on API/common.md
> +Проверяет ранее созданный ключ на соответствие паролю и стандарту шифрования. Возвращает `true`, если проверка пройдена, или выбрасывает исключение.
Поправил

2023-06-29 05:47 UTC, iMoonGoose commented on API/common.md
> +Проверяет ранее созданную лицензию на соответствие паролю и ключу и на соответсвие стандарту шифрования. Возвращает стандартный JS-объект с полями, указанными в исходной структуре лицензии, но у кажд
Поправил

2023-06-29 05:48 UTC, iMoonGoose commented on API/common.md
> +Интерфейс для работы с лицензиями воркспейса: получения информации об установленной на воркспейсе лицензии, создании шифрованной лицензионной строки и её валидации.
Поправил

2023-06-30 07:36 UTC, qx87 commented on API/common.md
> +Если на воркспейсе в панели администратора установлена лицензия, соответствующая зашитим в дистрибутив паролю и ключу, возвращает `true`. В противном случае возвращает `false`.
Была опечатка в слове "зашитым". Исправил сам.

2023-07-04 14:42 UTC, merged