[+] New 'MetricsManager' interface declaration #27378
optimacros/scripts_documentation pull request #55
Opened 2023-07-17 06:06 UTC by MrSheriff

2023-07-17 12:24 UTC, qx87 requested changes

2023-07-17 12:24 UTC, qx87 commented on API/common.md
> +export type MetricData = {
Пример описания типов в нашей документации: https://github.com/optimacros/scripts_documentation/blob/main/API/http.md#object-of-string-array

Лишнее слово export и скобки у полей.

2023-07-17 12:24 UTC, qx87 commented on API/common.md
> +setMetricValue(name: string, value: number, tags?: StringMap[]): MetricsManager;
Что такое StringMap?

2023-07-17 12:24 UTC, qx87 commented on API/common.md
> +### Интерфейс MetricsManager<a name="metrics-manager"></a>
Как получить доступ к интерфейсу MetricsManager? Возможно, через интерфейс OM или Common, но я не вижу изменений там.

2023-07-17 12:47 UTC, MrSheriff commented on API/common.md
> +export type MetricData = {
Не очень понял, так как именно так и описываются типы:
![image](https://github.com/optimacros/scripts_documentation/assets/6285250/c453bb1f-3ac5-4b4e-8dd4-e9773b3144ec)

2023-07-17 13:54 UTC, MrSheriff commented on API/common.md
> +### Интерфейс MetricsManager<a name="metrics-manager"></a>
Примеры использования:
```
    om.common.metricsManager().setMetricValue('test_metric', 12.1).setMetricValue('test_metric', 13.6, {'source': 'macroses', 'scope': 'incoming'}).setMetricValue('test_metric', 15.4, {'source': 'scripts', 'scope': 'incoming'});
    console.log(om.common.metricsManager().getMetricValue('test_metric') + '_' + om.common.metricsManager().getMetricValue('test_metric', {'source': 'macroses', 'scope': 'incoming'}) + '_' + om.common.metricsManager().getMetricValue('test_metric', {'source': 'scripts', 'scope': 'incoming'}));


    om.common.metricsManager().setMetricValue('test_metric', 12.6).setMetricValue('test_metric', 13.1, {'source': 'macroses', 'scope': 'incoming'}).setMetricValue('test_metric', 15.7, {'source': 'scripts', 'scope': 'incoming'});
    const metrics = om.common.metricsManager().getAllMetrics();
    for(let metric of metrics) {
        if (metric.name() === 'test_metric' && metric.tags() === 'incoming,scripts') {
            console.log(metric.name() + ': ' + metric.value() + ' (' + metric.tags() + ')');
        }
    }
```

2023-07-17 19:33 UTC, qx87 commented on API/common.md
> +export type MetricData = {
Это файл деклараций. В самой документации и у типов, и у интерфейсов опускается слово "export". 
А скобки в описании полей типа для чего? Это разве функции?

2023-07-17 19:34 UTC, qx87 commented on API/common.md
> +### Интерфейс MetricsManager<a name="metrics-manager"></a>
Его ещё нужно добавить в common.md.

2023-07-19 06:59 UTC, MrSheriff commented on API/common.md
> +### Интерфейс MetricsManager<a name="metrics-manager"></a>
Done

2023-07-19 06:59 UTC, MrSheriff commented on API/common.md
> +export type MetricData = {
> В самой документации и у типов, и у интерфейсов опускается слово "export"

Done

2023-07-21 11:05 UTC, m-golovkina requested changes

2023-07-21 11:12 UTC, MrSheriff commented on API/common.md
> +Тип `MetricData` описывает объекты метрик и предоставляет функции для доступа к имени метрики, её численому значению и к тегам метрики. Пример использования:
1,2 - done
3 - пусть тэги будут

2023-07-21 11:13 UTC, MrSheriff commented on API/common.md
> +getAllMetrics(): MetricData[];
Done

2023-07-21 11:19 UTC, MrSheriff commented on API/common.md
> +Сохраняет метрику с именем `name` и тегами `tags`, присваивая ей численное значением `value`. Возвращает `this`.
Done

2023-07-21 11:19 UTC, MrSheriff commented on API/common.md
> +Возвращает численное значение метрики с именем `name` и тегами `tags`, или `null`, если метрика не существует.
Done

2023-07-21 11:57 UTC, m-golovkina approved these changes

2023-07-21 14:26 UTC, merged