Exporter and StorageExporter reference fixed
optimacros/scripts_documentation pull request #58
Opened 2023-08-11 13:48 UTC by qx87

https://rucom.optimacros.com/topic/33031

2023-08-11 13:51 UTC, qx87 commented
Протестировал интерфейс Exporter. У его функций действительно отличается поведение от функций CSVParams: отсылку "методы интерфейса X работают аналогично методам интерфейса Y" нельзя делать ни в одну, ни в другую сторону, описание теперь разное. Хотя и похожее.

2023-08-18 13:10 UTC, qx87 commented
Тесты есть в первом скрипте здесь: https://ws116.optimacros.com/?modelId=67e842c0475a226bcbfec79a977806d5#eyJ0eXBlIjoiTWFjcm9zU2NyaXB0c0J1aWxkZXJUYWIiLCJwYXJhbXMiOnsiYWN0aXZlVGFiIjowfX0=

2023-08-21 10:23 UTC, m-golovkina requested changes

2023-08-22 09:16 UTC, qx87 commented on API/exportImport.md
> +Устанавливает разделитель полей. При использовании для интерфейса [`CsvReader`](./csv.md#csv-reader) должен быть однобайтным символом. При использовании для интерфейса [`CsvWriter`](./csv.md#csv-writ
Исправил.

2023-08-22 11:27 UTC, m-golovkina requested changes

2023-08-22 11:27 UTC, m-golovkina commented on API/exportImport.md
> +Устанавливает обрамляющий символ, которым будет обрамляться текстовое поле, если в нём содержится разделитель полей, пробел, табуляция или сам обрамляющий символ. Допустим лишь один однобайтовый симв
Извини, забыла еще тут оставить коммент - И если в поле содержится символ переноса строки еще (lineDelimiter)

2023-08-22 15:16 UTC, m-golovkina approved these changes

2023-08-22 15:17 UTC, merged

2024-09-10 15:58 UTC, gelotometrist commented
> Тесты есть в первом скрипте здесь: https://ws116.optimacros.com/?modelId=67e842c0475a226bcbfec79a977806d5#eyJ0eXBlIjoiTWFjcm9zU2NyaXB0c0J1aWxkZXJUYWIiLCJwYXJhbXMiOnsiYWN0aXZlVGFiIjowfX0=

Есть ли примеры использования Exporter? Доступа к модели нет, а необходимость сейчас есть использовать этот функционал