34559 - Scripts Storage Read Mode
optimacros/scripts_documentation pull request #63
Opened 2023-11-09 07:49 UTC by Toxin4ick

2023-11-10 12:47 UTC, m-golovkina requested changes

2023-11-10 12:47 UTC, m-golovkina commented on API/common.md
> +    	getCurrentMacrosStorageReadMode(): string;
Этот метод возвращает не только `string`. Он возвращает `null`, если `setCurrentMacrosStorageReadMode()` еще не был вызван в скрипте. И как тогда понять, какой режим стоит у скрипта при его запуске.

2023-11-10 12:47 UTC, m-golovkina commented on API/common.md
> +    	getModelMacrosStorageReadMode(): string;
Эти методы не существуют в `ModelInfo()`

2023-11-10 12:47 UTC, m-golovkina commented on API/common.md
> +Устанавливает режим чтения в скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что при кажд
Устанавливает режим чтения в **текущем** скрипте.

2023-11-10 12:47 UTC, m-golovkina commented on API/common.md
> +Возвращает режим чтения скрипта. Возвращаемое значение может быть одно из `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`.
Возвращает режим чтения **в текущем** скрипте.

2023-11-10 12:47 UTC, m-golovkina commented on API/common.md
> +Возвращает установленный режим чтения модели для скриптов (одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`).
...режим чтения **В** модели для скриптов

2023-11-13 16:54 UTC, m-golovkina commented on API/common.md
> +setModelMacrosStorageReadMode(type: string): boolean;
Добавить к описанию, что метод ожидает завершения всех запросов в модели и только после переключает режим

2023-12-12 18:51 UTC, m-golovkina approved these changes

2023-12-13 11:13 UTC, m-golovkina commented on changelog.html
> +                        <td></td>
Здесь нужно будет ссылку добавить с тегами после слития

2023-12-14 11:30 UTC, qx87 requested changes

2023-12-14 11:30 UTC, qx87 commented on API/common.md
> +Устанавливает режим чтения в текущем скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что
Мы находимся в интерфейсе Common, где расположены ссылки на максимально общие интерфейсы. Режим чтения чего устанавливает функция?

2023-12-14 11:30 UTC, qx87 commented on API/common.md
> +Устанавливает режим чтения в текущем скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что
Не "в параметре принимает", а "параметр `type` принимает".

2023-12-14 11:30 UTC, qx87 commented on API/common.md
> +Устанавливает режим чтения в текущем скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что
Значения строковых констант везде по тексту нужно обернуть в одинарные кавычки. Вот так: `'CONSISTENT_READ'`.

2023-12-14 11:30 UTC, qx87 commented on API/common.md
> +Устанавливает режим чтения в текущем скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что
До чего существовал 'CONSISTENT_READ'?

2023-12-14 11:30 UTC, qx87 commented on API/common.md
> +	getCurrentMacrosStorageReadMode(): string;
Поскольку в Common теперь добавлены функции, нужно изменить его описание.

2023-12-15 11:37 UTC, m-golovkina commented on API/common.md
> +	getCurrentMacrosStorageReadMode(): string;
Добавила в описание `... интерфесы и методы`

2023-12-15 11:39 UTC, m-golovkina commented on API/common.md
> +Устанавливает режим чтения в текущем скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что
Я эту часть текста вообще удалила. Считаю это лишней информацией

2023-12-15 11:40 UTC, m-golovkina commented on API/common.md
> +Устанавливает режим чтения в текущем скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что
Готово

2023-12-15 11:41 UTC, m-golovkina commented on API/common.md
> +Устанавливает режим чтения в текущем скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что
Исправлено

2023-12-15 11:42 UTC, m-golovkina commented on API/common.md
> +Устанавливает режим чтения в текущем скрипте. В параметре принимает одно из значений `CONSISTENT_READ`, `FAST_READ`, `FAST_READ_METADATA`. `CONSISTENT_READ` существовал и до этого и гарантирует, что
Дописала везде `режим чтения данных в модели`

2023-12-18 18:28 UTC, m-golovkina commented on API/common.md
> +Устанавливает режим чтения данных в модели для текущего скрипта. Параметр `type` принимает одно из значений `'CONSISTENT_READ'`, `'FAST_READ'`, `'FAST_READ_METADATA'`. Режим `'CONSISTENT_READ'` гаран
Исправлено

2023-12-18 18:29 UTC, m-golovkina commented on API/common.md
> +Устанавливает режим записи данных в модели. Аналог в интерфейсе `Optimacros`: `Меню пользователя` -> `Параметры` -> `Расширенные` -> `Режим записи`. Параметр `type` принимает одно из значений `'CONSI
Исправлено

2023-12-20 09:30 UTC, qx87 requested changes
Я сам исправил последние опечатки и после этого стал вчитываться в смысл.

1. Режимы чтения и режимы записи у двух групп функций одинаковые. Из-за этого любые опечатки приходилось править несколько раз. Любые будущие изменения тоже придётся править по нескольку раз. Стоит вынести эти два описания режимов в отдельное место, и в описаниях функций давать на него ссылку.

2. Добавлено несколько функций со смежным функционалом, причём в разные места. Читая функции интерфейса Common, не очевидно, что похожие функции есть в ModelInfo. И даже читая потом их все вместе, может быть трудно разобраться, когда какую стоит использовать, особенно при цепочках скриптов. Я думаю, нужно описать особенности их использования. Например, сделать короткую статью в https://github.com/optimacros/scripts_documentation/blob/main/advancedFeatues/advancedFeatues.md. Туда же, кстати, можно положить описания режимов.

2023-12-22 12:23 UTC, merged