18378 Notification Center
optimacros/scripts_documentation pull request #64
Opened 2023-11-20 12:13 UTC by MrSheriff

https://rucom.optimacros.com/topic/18378

2024-03-04 12:43 UTC, iMoonGoose requested changes
Не увидел, что с важностью, можно ли её управлять?
![image](https://github.com/optimacros/scripts_documentation/assets/62833016/a31420ec-3f25-47bb-989d-07d59d63472e)
Не понял, как будут взаиможействовать каналы (он будет всегда один без возможности создать пользователю свой или сколько угодно), группы и т.д.:
![image](https://github.com/optimacros/scripts_documentation/assets/62833016/5dc0debb-5fe2-4cfb-9c36-56c0a65ce3a6)

2024-03-04 12:43 UTC, iMoonGoose commented on API/notifications.md
> +Устанавливает адресата или адресатов. Возвращает `this`.
Что сдесь нужно передавать? Почту? Имя и фамилию? `longId` элемента справочника `Users`?

2024-03-04 12:43 UTC, iMoonGoose commented on API/notifications.md
> +Устанавливает тему уведомления. Возвращает `this`.
Какие есть ограничения на это поле? Длина?

2024-03-04 12:43 UTC, iMoonGoose commented on API/notifications.md
> +Устанавливает тело уведомления. Возвращает `this`.
Какие есть ограничения на это поле? Длина? Есть ли возможность форматирования или только plain text?

2024-03-04 12:43 UTC, iMoonGoose commented on API/notifications.md
> +Запускает механизм асинхронной отправки уведомления. Возвращает интерфейс [`Web.Result`](#web.result).
Как он работает? Где прочитать?

2024-03-04 12:43 UTC, iMoonGoose commented on API/notifications.md
> +Интерфейс доступа к результатам отправки уведомления. Содержит строку `messageId` с идентификатором отправленного уведомления.
Что это за идентификатор? Где он используется, кроме этого интерфейса? В админке воркспейса в отправленных уведомлениях? На ФЕ?

2024-03-05 13:29 UTC, MrSheriff commented on API/notifications.md
> +Устанавливает адресата или адресатов. Возвращает `this`.
> Не понял, как будут взаиможействовать каналы (он будет всегда один без возможности создать пользователю свой или сколько угодно)

Каналы создаются в админке.

2024-03-05 13:29 UTC, MrSheriff commented on API/notifications.md
> +Устанавливает адресата или адресатов. Возвращает `this`.
> Что сдесь нужно передавать? Почту?

Почту

2024-03-05 13:39 UTC, MrSheriff commented on API/notifications.md
> +Устанавливает тело уведомления. Возвращает `this`.
Есть ограничения - 262144 символов (256 kb). plain text

2024-03-05 13:42 UTC, MrSheriff commented on API/notifications.md
> +Запускает механизм асинхронной отправки уведомления. Возвращает интерфейс [`Web.Result`](#web.result).
Так же как и send() у Smtp.Builder Прочитать пока нельзя
![image](https://github.com/optimacros/scripts_documentation/assets/6285250/a46d0d9c-debd-4c52-9a67-fe9687f24f9f)

2024-03-05 13:43 UTC, MrSheriff commented on API/notifications.md
> +Интерфейс доступа к результатам отправки уведомления. Содержит строку `messageId` с идентификатором отправленного уведомления.
Да в админке можно найти уведомление по этому идентификатору.

2024-03-05 15:40 UTC, iMoonGoose commented on API/notifications.md
> +Устанавливает тело уведомления. Возвращает `this`.
256 kb или 262144 символов? В UTF-8 один символ может занимать несколько байт

2024-03-06 06:30 UTC, iMoonGoose requested changes

2024-03-06 06:30 UTC, iMoonGoose commented on API/notifications.md
> +◾️ `'%URGENT_NOTICE%'` - повышает важность сообщения, может быть использованно при отображении уведомления на клиенте<br>
Лучше сделать отдельный метод `markUrgent(): this`, что он там под капотом делать будет неважно, но мешать в одну кучу адресатов и флаги — плохая идея

2024-03-06 06:30 UTC, iMoonGoose commented on API/scripts.om.d.ts
> +    namespace Web {
Стоит добавить в декларацию существующий канал по умолчанию
```ts
export const enum Preset {
    CommonChannel: 'WEB notices',
}
```

2024-03-06 06:30 UTC, iMoonGoose commented on API/scripts.om.d.ts
> +    namespace Web {
Названия групп тоже логично указать перечислением
```
export const enum GroupAlias {
    AllUsers = '%ALL_USERS%',
    ...
}
```

2024-03-06 06:30 UTC, iMoonGoose commented on API/notifications.md
> +	web(channel: string): Web.Builder;
Что с вот этим?
![image](https://github.com/optimacros/scripts_documentation/assets/62833016/150fc568-f04e-4b6b-a939-399abb4171d2)

2024-03-06 06:38 UTC, MrSheriff commented on API/notifications.md
> +	web(channel: string): Web.Builder;
Это не реализовано на данном этапе. Это же эпик, это просто пункт на будущее.

2024-03-06 06:50 UTC, iMoonGoose commented on API/notifications.md
> +	web(channel: string): Web.Builder;
А в каком виде планируется реализация? Примерно как группы пользователей, которые уже сделаны?

2024-03-06 07:05 UTC, MrSheriff commented on API/notifications.md
> +◾️ `'%URGENT_NOTICE%'` - повышает важность сообщения, может быть использованно при отображении уведомления на клиенте<br>
Добавил отдельный метод

2024-03-06 07:05 UTC, MrSheriff commented on API/notifications.md
> +	web(channel: string): Web.Builder;
Пока это даже не обсуждалось.

2024-03-06 07:22 UTC, MrSheriff commented on API/scripts.om.d.ts
> +    namespace Web {
Добавил

2024-03-06 07:22 UTC, MrSheriff commented on API/scripts.om.d.ts
> +    namespace Web {
Добавил

2024-03-06 09:13 UTC, iMoonGoose approved these changes

2024-03-06 10:56 UTC, kolyan-r approved these changes

2024-05-08 08:56 UTC, merged