43080 - add audit API
optimacros/scripts_documentation pull request #66
Opened 2023-11-27 05:30 UTC by Toxin4ick

https://rucom.optimacros.com/topic/43080/возможность-работать-скриптами-с-гридом-аудита?_=1700455761298

2023-11-28 13:34 UTC, iMoonGoose requested changes

2023-11-28 13:34 UTC, iMoonGoose commented on API/dimensions.md
> +dateFilter(data: string[] | string | number | number[]): AuditPivot
Нужно указать, что первая дата включительно, вторая — нет

2023-11-28 13:34 UTC, iMoonGoose commented on API/dimensions.md
> +    	dateFilter(beginAt?: string | number, endAt?:  string | number): AuditPivot
Проверил, параметры можно указать как `undefined` или `null`, стоит это указать

2023-11-28 13:34 UTC, iMoonGoose commented on API/dimensions.md
> +dateFilter(data: string[] | string | number | number[]): AuditPivot
При указании в формате Unix Time явно есть разница в часовом поясе между тем, что отображается в веб-интерфейсе и как считает метод. Нужно написать в каком часовом поясе видно на вкладке (и в выгрузке), а в каком нужно передавать настройку

2023-11-29 06:13 UTC, Toxin4ick commented on API/dimensions.md
> +	auditPivot(): AuditPivot
Поправил

2023-11-29 07:21 UTC, Toxin4ick commented on API/dimensions.md
> +Позволяет ограничить отображаемые строки по колонке **Details4**. Функция будет работать, только если перед этим было произведено ограничение по типу события `Изменение значения клетки`.
Поправлю

2023-11-29 07:21 UTC, Toxin4ick commented on API/dimensions.md
> +dateFilter(data: string[] | string | number | number[]): AuditPivot
Поправлю

2023-11-30 08:32 UTC, Toxin4ick commented on API/dimensions.md
> +eventTypeFilter(data: string[] | string | number | number[]): AuditPivot
Добавил таблицей

2023-11-30 08:32 UTC, Toxin4ick commented on API/dimensions.md
> +dateFilter(data: string[] | string | number | number[]): AuditPivot
поправил

2023-11-30 08:32 UTC, Toxin4ick commented on API/dimensions.md
> +    	dateFilter(beginAt?: string | number, endAt?:  string | number): AuditPivot
указал

2023-11-30 08:33 UTC, Toxin4ick commented on API/dimensions.md
> +Позволяет ограничить отображаемые строки по колонке **Details4**. Функция будет работать, только если перед этим было произведено ограничение по типу события `Изменение значения клетки`.
Тут обсуждение с Ильёй Нужно

2023-11-30 10:26 UTC, iMoonGoose requested changes
Поправлено не всё

2023-11-30 10:26 UTC, iMoonGoose commented on API/dimensions.md
> +Примеры дат в виде строк:
У меня проходил формат `dd.mm.yyyy`, но не проходил `dd/mm/yyyy`, нужно указать, какой библиотекой, по какому правилу осуществляется конвертация

2023-11-30 10:26 UTC, iMoonGoose commented on API/dimensions.md
> +Позволяет ограничить отображаемые строки по дате в диапазоне от и до. Даты можно писать в виде строки на английском языке/даты/времени, примеры ниже. Так же даты можно передать в виде Unix time значе
1.Не указано, в каком часовом поясе отображается время в аудите в веб-интрефейсе.
2. В декларации не добавлено `undefined` и `null`

2023-12-14 03:13 UTC, Toxin4ick commented on API/dimensions.md
> +Примеры дат в виде строк:
Добавил ссылку на все допустимые форматы даты и времени

2023-12-27 10:26 UTC, iMoonGoose approved these changes

2024-01-11 13:41 UTC, m-golovkina approved these changes

2024-01-12 10:18 UTC, qx87 approved these changes

2024-01-12 10:28 UTC, merged