Upgrade description of CopyData
optimacros/scripts_documentation pull request #72
Opened 2024-01-22 11:55 UTC by qx87

2024-01-23 14:02 UTC, m-golovkina requested changes

2024-01-24 16:22 UTC, qx87 commented on API/common.md
> +- вызвать них функции `setSourceLongId()` и `setDestLongId()` на двух элементах одного и того же измерения, которое здесь будем называть *заданным измерением*;
Исправил.

2024-01-24 16:22 UTC, qx87 commented on API/common.md
> +- указать кубы, срезы в которых нужно копировать, вызовом одной из четырёх функций: `enableCopyAllCubes()`, `enableCustomProperties()`, `setMulticubeLongIds()`, `setMulticubeByNames()`;
Исправил.

2024-01-24 16:25 UTC, qx87 commented on API/common.md
> +Интерфейс, реализующий шаблон проектирования [`строитель`](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%BE%D0%B8%D1%82%D0%B5%D0%BB%D1%8C_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%B
При чтении первого предложения это и не должно пока ещё быть понятно. Речь пока что о том, что у нас будет копирование из одних кубов в другие. Далее поясняется, что эти другие кубы задаются вызовом одной из 4 функций. На мой взгляд здесь всё правильно.

2024-01-24 16:26 UTC, qx87 commented on API/common.md
> +Устанавливает [`longId`](./views.md#long-id) элемента измерения источника.
Ок.

2024-01-24 16:26 UTC, qx87 commented on API/common.md
> +Устанавливает [`longId`](./views.md#long-id) элемента измерения приёмника.
Ок.

2024-01-24 16:36 UTC, qx87 commented on API/common.md
> +Предписывает произвести копирование в пользовательских свойствах всех справочников модели, которые содержат *заданное измерение*.
Измерениями являются, например, справочник и его сабсеты. Если элемент-источник содержится в нескольких сабсетах, то копирование будет по всем кубам, которые содержат любой из этих сабсетов или сам справочник целиком как измерение.

2024-01-24 16:37 UTC, qx87 commented on API/common.md
> +Предписывает произвести копирование во всех кубах модели, содержащих *заданное измерение*.
Но кубы же строятся не на одном измерении. Предлагать оставить. А если настаиваешь, давай обсудим на чипидейли.

2024-01-28 09:39 UTC, qx87 commented on API/common.md
> +Интерфейс, реализующий шаблон проектирования [`строитель`](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%BE%D0%B8%D1%82%D0%B5%D0%BB%D1%8C_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%B
Исправил.

2024-01-28 09:39 UTC, qx87 commented on API/common.md
> +- вызвать них функции `setSourceLongId()` и `setDestLongId()` на двух элементах одного и того же измерения, которое здесь будем называть *заданным измерением*;
Исправил.

2024-01-28 09:40 UTC, qx87 commented on API/common.md
> +- указать кубы, срезы в которых нужно копировать, вызовом одной из четырёх функций: `enableCopyAllCubes()`, `enableCustomProperties()`, `setMulticubeLongIds()`, `setMulticubeByNames()`;
Исправил.

2024-01-28 09:40 UTC, qx87 commented on API/common.md
> +Устанавливает [`longId`](./views.md#long-id) элемента измерения источника.
Исправил.

2024-01-28 09:41 UTC, qx87 commented on API/common.md
> +Устанавливает [`longId`](./views.md#long-id) элемента измерения приёмника.
Исправил.

2024-01-29 15:37 UTC, m-golovkina commented on API/common.md
> +Предписывает произвести копирование в пользовательских свойствах всех справочников модели, которые содержат *заданное измерение*.
мне все таки не нравиться фраза `...всех справочников модели, которые содержат заданное измерение.`  Давай так `в пользовательских свойствах заданного измерения.`

2024-01-31 06:17 UTC, qx87 commented on API/common.md
> +Предписывает произвести копирование в пользовательских свойствах всех справочников модели, которые содержат *заданное измерение*.
А если у нас есть родительский справочник?

2024-01-31 10:44 UTC, m-golovkina approved these changes

2024-01-31 10:45 UTC, merged