47517 Ability to work with model users grid by scripts
optimacros/scripts_documentation pull request #74
Opened 2024-02-05 07:31 UTC by Toxin4ick

https://rucom.optimacros.com/topic/47517/возможность-работать-скриптами-с-таблицей-пользователей-модели-model-users

2024-02-14 10:12 UTC, kolyan-r approved these changes

2024-02-29 05:12 UTC, iMoonGoose requested changes
Мелкие правки

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +Интерфейс для получения доступа к гридам пользователей в модели.
Лучше избегать слова `грид`: сторонние люди не поймут. Можно заменять на `таблица`

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +[`Grid`](./views.md#grid) данного [`Tab`](./views.md#tab) доступен только пользователям с правами моделера.
А грид ли? Ошибка недостаточного доступа вылетит при получении таба или грида?

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +Для [`Pivot`](./views.md#интерфейс-pivot) данного [`Tab`](./views.md#tab) не работают мотоды:
Нужно написать, что есть только представление по умолчанию

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +У [`Grid`](./views.md#grid) недоступны методы:
Нужно написать, что за измерение находится в строках грида

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +Для изменения натроек пользователей нужна роль равная им или выше. (Моделер -> Администратор -> Сервисный администратор)
Для изменения натроек пользователей нужна роль равная им или выше: `Моделер` -> `Администратор` -> `Сервисный администратор`.

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +Вкладка `Другие пользователи сервера`. Содержит пользхователей воркспейса, у которых нет доступа к даннй модели и их настройки. Интерфейс наследуется от [`Tab`](./views.md#tab). Доступен только польз
по**льзх**ователей

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +Для изменения натроек пользователей нужна роль равная им или выше. (Моделер -> Администратор -> Сервисный администратор)
**нат**роек

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +Для [`Pivot`](./views.md#интерфейс-pivot) данного [`Tab`](./views.md#tab) не работают мотоды:
Те же вопросы по доступности толькл представления по умолчанию и измерению в строках

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +
А `storageExporter()` доступен?

2024-02-29 05:12 UTC, iMoonGoose commented on changelog.html
> +                                    Добалена возможность читать пользователей модели и воркспейса из скриптов. Смотреть интерфейс <a href="https://github.com/optimacros/scripts_documentation/blob/mai
Не только читать, но и редактировать

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +Вкладка `Другие пользователи сервера`. Содержит пользхователей воркспейса, у которых нет доступа к даннй модели и их настройки. Интерфейс наследуется от [`Tab`](./views.md#tab). Доступен только польз
Нужно написать, что при изменении роли пользователя на любую, кроме `no access`. Пользователь переедет в другую вкладку (но изменение других клеток для этого же пользователя после измения роли в рамках **того же** генератора будет проходить без проблем).

2024-02-29 05:12 UTC, iMoonGoose commented on API/users.md
> +Вкладка `Пользователи модели`. Содержит пользователей модели и их настройки. Интерфейс наследуется от [`Tab`](./views.md#tab).
Нужно написать, что при изменении роли пользователя на `no access`. Пользователь переедет в другую вкладку (но изменение других клеток для этого же пользователя после измения роли в рамках **того же** генератора будет проходить без проблем).

2024-02-29 08:21 UTC, pahMelnik commented on API/API.md
>  * взаимодействие с моделью, как сущностью: создание бэкапа, пересчёт всей модели (см. `Common.ModelInfo`);
Готово

2024-02-29 08:22 UTC, pahMelnik commented on API/API.md
> +    readonly users: Users;
Готово

2024-02-29 08:24 UTC, pahMelnik commented on API/users.md
> +Интерфейс для получения доступа к гридам пользователей в модели.
Готово

2024-02-29 08:30 UTC, pahMelnik commented on API/users.md
> +Вкладка `Пользователи модели`. Содержит пользователей модели и их настройки. Интерфейс наследуется от [`Tab`](./views.md#tab).
Готово

2024-02-29 08:46 UTC, pahMelnik commented on API/users.md
> +[`Grid`](./views.md#grid) данного [`Tab`](./views.md#tab) доступен только пользователям с правами моделера.
Да грид

2024-02-29 08:48 UTC, pahMelnik commented on API/users.md
> +Для [`Pivot`](./views.md#интерфейс-pivot) данного [`Tab`](./views.md#tab) не работают мотоды:
Готово

2024-02-29 08:51 UTC, pahMelnik commented on API/users.md
> +У [`Grid`](./views.md#grid) недоступны методы:
Готово

2024-02-29 08:52 UTC, pahMelnik commented on API/users.md
> +Для изменения натроек пользователей нужна роль равная им или выше. (Моделер -> Администратор -> Сервисный администратор)
Готово

2024-02-29 08:52 UTC, pahMelnik commented on API/users.md
> +Для изменения натроек пользователей нужна роль равная им или выше. (Моделер -> Администратор -> Сервисный администратор)
Готово

2024-02-29 08:53 UTC, pahMelnik commented on API/users.md
> +Вкладка `Другие пользователи сервера`. Содержит пользхователей воркспейса, у которых нет доступа к даннй модели и их настройки. Интерфейс наследуется от [`Tab`](./views.md#tab). Доступен только польз
Готово

2024-02-29 08:54 UTC, pahMelnik commented on API/users.md
> +Вкладка `Другие пользователи сервера`. Содержит пользхователей воркспейса, у которых нет доступа к даннй модели и их настройки. Интерфейс наследуется от [`Tab`](./views.md#tab). Доступен только польз
Готово

2024-02-29 09:02 UTC, pahMelnik commented on API/users.md
> +Для [`Pivot`](./views.md#интерфейс-pivot) данного [`Tab`](./views.md#tab) не работают мотоды:
Готово

2024-02-29 09:04 UTC, pahMelnik commented on API/users.md
> +
Нет, добавил

2024-02-29 09:05 UTC, pahMelnik commented on changelog.html
> +                                    Добалена возможность читать пользователей модели и воркспейса из скриптов. Смотреть интерфейс <a href="https://github.com/optimacros/scripts_documentation/blob/mai
Готово

2024-02-29 09:40 UTC, iMoonGoose approved these changes

2024-02-29 09:48 UTC, merged