49054 crypto sha1
optimacros/scripts_documentation pull request #75
Opened 2024-02-09 09:26 UTC by johnrembo

https://rucom.optimacros.com/topic/49054

2024-02-09 11:56 UTC, MrSheriff commented on API/scripts.om.d.ts
> +     * @param string $data: Message to be hashed
Тут в .ts так @param вроде как не описываются с типами.

```
    /**
     * @param $data Message to be hashed
     * @param $binary When set to true, outputs raw binary data. false outputs lowercase hexits
     */

2024-02-09 11:56 UTC, MrSheriff requested changes
Minor comments

2024-02-12 07:38 UTC, johnrembo commented on API/scripts.om.d.ts
> +     * @param string $data: Message to be hashed
перезалито для 44447

2024-02-12 08:02 UTC, svowl requested changes

2024-02-12 08:02 UTC, svowl commented on API/common.md
> +    requestSignatureManager(): RequestSignatureManager;
отступы сбились

2024-02-12 08:02 UTC, svowl commented on API/common.md
> +```
убери пстую строку

2024-02-12 08:02 UTC, svowl commented on API/common.md
> +}
убери пстую строку

2024-02-12 08:02 UTC, svowl commented on API/scripts.om.d.ts
> +
убери пстую строку

2024-02-12 08:05 UTC, svowl commented on API/common.md
> +```
что такое jd?

2024-02-12 08:15 UTC, johnrembo commented on API/common.md
> +}
в коде с пустой строкой, а здесь не надо?

2024-02-12 08:15 UTC, johnrembo commented on API/common.md
> +```
опечатка. вижу теперь

2024-02-12 08:15 UTC, johnrembo commented on API/common.md
> +    requestSignatureManager(): RequestSignatureManager;
это не отступы. там табы выше.

2024-02-12 08:23 UTC, johnrembo commented on API/scripts.om.d.ts
> +
ок

2024-02-12 11:30 UTC, MrSheriff commented on API/common.md
> +&nbsp;
&nbsp; - зачем?

2024-02-12 11:31 UTC, MrSheriff commented on API/common.md
> +	sha1(data: string, binary: boolean): string
Что как много пробелов для отступа?

2024-02-12 11:32 UTC, MrSheriff requested changes
Some remarks

2024-02-12 11:34 UTC, johnrembo commented on API/common.md
> +	sha1(data: string, binary: boolean): string
это таб, решили так для единообразия

2024-02-12 11:34 UTC, johnrembo commented on API/common.md
> +&nbsp;
для единообразия

2024-02-12 12:16 UTC, MrSheriff approved these changes

2024-02-12 12:41 UTC, iMoonGoose commented on API/scripts.om.d.ts
> +    sha1($data:string , $binary:boolean = false): string
1. Непонятно, зачем отдельный метод для алгоритма, логичнее сделать общий с выбором алгоритма
2. Знаки долара в начале имени переменных не нужны
3. Непонятен тип возвращаемых данных, если `binary = true`
4. `binary` лучше переименовать в `binaryOutput`
5. `data` может быть только строкой? Что насчёт `ArrayBuffer` и его примения?

2024-02-13 15:18 UTC, MrSheriff commented on API/common.md
> +Возвращает SHA1-хэш строки `data` в UTF-8, вычисленный по алгоритму US Secure Hash Algorithm 1 в виде 40-символьного шестнадцатеричного числа. Пример использования:
Я бы указал тут
```
[`SHA1-хэш`](https://en.wikipedia.org/wiki/SHA-1)
```

2024-02-13 15:21 UTC, MrSheriff requested changes
Minor remarks

2024-02-13 15:25 UTC, johnrembo commented on API/common.md
> +Возвращает SHA1-хэш строки `data` в UTF-8, вычисленный по алгоритму US Secure Hash Algorithm 1 в виде 40-символьного шестнадцатеричного числа. Пример использования:
добавлено

2024-02-14 10:05 UTC, kolyan-r approved these changes

2024-02-14 10:14 UTC, MrSheriff approved these changes

2024-02-14 10:56 UTC, iMoonGoose approved these changes

2024-02-20 10:17 UTC, svowl approved these changes

2024-02-20 10:19 UTC, merged