44447 - SDK API for HMAC
optimacros/scripts_documentation pull request #78
Opened 2024-02-26 07:51 UTC by MrSheriff

https://rucom.optimacros.com/topic/44447

2024-02-27 05:38 UTC, iMoonGoose requested changes

2024-02-27 05:40 UTC, iMoonGoose requested changes
Не отредактирован `scripts.om.d.ts`

2024-02-27 07:24 UTC, MrSheriff commented on API/crypto.md
> +В случае ошибки (не прошла валидация входных параметров или что-то ещё) возвращается `null`.
Валидация аргументов делается ещё и внутри функций. Это стандартное поведение.

2024-02-27 07:25 UTC, MrSheriff commented on API/crypto.md
> +Если `binary` выставлено в `true`, то хэш возвращается в виде бинарных данных.<br>
Бинарные данные = это тоже строка. Это особенность этих функций.

2024-02-27 07:33 UTC, MrSheriff commented on API/crypto.md
> +hash(algo: string , data: string , binary?: boolean): string | null
Да: "Если `binary` не выставлено в `true` (по умолчание не выставлено)"

2024-02-27 07:33 UTC, MrSheriff commented on API/crypto.md
> +hmac(algo: string, data: string, key: string, binary?: boolean): string | null
Да: "Если `binary` не выставлено в `true` (по умолчание не выставлено)"

2024-02-27 07:36 UTC, MrSheriff commented on API/crypto.md
> +Возвращает [`HMAC (Hash-based Message Authentication Code)`](https://ru.wikipedia.org/wiki/HMAC) для строки `data` (переданной в кодировке `UTF-8`) с использованием переданного `key`. Аналогично `has
Да. Добавил.

2024-02-27 07:44 UTC, MrSheriff commented on API/crypto.md
> +Если `binary` выставлено в `true`, то hmac возвращается в виде бинарных данных, закодированных с помощью Base64 в формате "==Base64String==".<br>
> почему сразу не вернуть чистую строку
Потому что возвращаемое значение может быть использованно в качестве `key` в цепочке вызовов:
```
const dateKey = om.crypto.hmac(algo, dateValue, secretKey, true);
const regionKey = om.crypto.hmac(algo, regionValue, dateKey, true);
const serviceKey = om.crypto.hmac(algo, serviceValue, regionKey, true);
const signingKey = om.crypto.hmac(algo, signingValue , serviceKey, true);
const signature = om.crypto.hmac(algo, stringToSign, signingKey);
```
Без использования оборачивания нет возможности узнать, какой ключ был получен в результате работы `hmac`, а какой просто использован извне.

> зачем использовать для оборачивания символ, имеющий значение в кодировке
Чтобы не плодить сущности и не заморачиваться с выбором нового символа.

2024-02-27 07:47 UTC, MrSheriff commented on API/crypto.md
> +getHmacAlgorithms(): string[]
Переименовал

2024-02-27 07:48 UTC, MrSheriff commented on API/crypto.md
> +	sha1(data: string): string | null;
Нет. Решили оставить

2024-02-27 08:30 UTC, iMoonGoose requested changes
Всё ещё нет `scripts.om.d.ts`

2024-02-27 08:30 UTC, iMoonGoose commented on API/crypto.md
> +	sha1(data: string): string | null;
Кто решил? Какие аргументы?

2024-02-27 08:30 UTC, iMoonGoose commented on API/crypto.md
> +В случае ошибки (не прошла валидация входных параметров или что-то ещё) возвращается `null`.
Плохое поведение. Для тех случаев, когда функция не может вернуть значение, есть выбрасывание исключений. `null` — это значение и его появляение должно быть обосновано. Хэш не может быть нулл, его или можно посчитать и он соответствующего формата, или ошибка (не тот формат данных, короткая строка, хз что еще)

2024-02-27 08:30 UTC, iMoonGoose commented on API/crypto.md
> +hash(algo: string , data: string , binary?: boolean): string | null
https://www.typescripttutorial.net/typescript-tutorial/typescript-default-parameters/
```
hash(algo: string, data: string, binary: boolean = false)
```

2024-02-27 08:30 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary` выставлено в `true`, то хэш возвращается в виде бинарных данных.<br>
Так а в каком формате они выдаются?

2024-02-27 08:30 UTC, iMoonGoose commented on API/crypto.md
> +hmac(algo: string, data: string, key: string, binary?: boolean): string | null
Аналогично тому, что выше

2024-02-27 08:30 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary` выставлено в `true`, то hmac возвращается в виде бинарных данных, закодированных с помощью Base64 в формате "==Base64String==".<br>
Для чего это нужно? Почему существует такое костыльное поведени? Почему не изменить символ оборачивания? Хоть на `%`, хоть на `|`

2024-02-27 09:42 UTC, MrSheriff commented on API/crypto.md
> +Если `binary` выставлено в `true`, то hmac возвращается в виде бинарных данных, закодированных с помощью Base64 в формате "==Base64String==".<br>
> Для чего это нужно? 
Это сделано на основе трбований заказчика.

> Почему не изменить символ оборачивания?
А на что это влияет? Зачем изменять символ оборачивания? Чем не устраивает `=` ? Чем он отличается от % или |  ?

2024-02-27 09:43 UTC, MrSheriff commented on API/crypto.md
> +	sha1(data: string): string | null;
Команда MW и PM

2024-02-27 09:55 UTC, kolyan-r approved these changes

2024-02-27 09:55 UTC, kolyan-r commented on API/crypto.md
> +	sha1(data: string): string | null;
решили оставить

2024-02-27 10:00 UTC, MrSheriff commented on API/crypto.md
> +Если `binary` выставлено в `true`, то хэш возвращается в виде бинарных данных.<br>
В бинарном. Просто в строке бинарные данные.
![image](https://github.com/optimacros/scripts_documentation/assets/6285250/b15f52fc-2928-4a0a-95a6-a83c524b239f)

2024-02-27 10:13 UTC, MrSheriff commented on API/crypto.md
> +hash(algo: string , data: string , binary?: boolean): string | null
Не видел **ни одного** примера в `scripts_documentation`, где так указываются параметры по умолчанию.
![image](https://github.com/optimacros/scripts_documentation/assets/6285250/cedac219-9d0f-4632-a85f-b4cdbaaee7f0)
Почему только сейчас это возникло?
Это должно быть только в `crypto.md` ?
Потому что, например, в `scripts.om.d.ts` я вижу такой вот warning:
![image](https://github.com/optimacros/scripts_documentation/assets/6285250/5d5b3d33-fbbb-474a-9111-f8d7e15ab39c)

2024-02-27 10:14 UTC, MrSheriff commented on API/crypto.md
> +hash(algo: string , data: string , binary?: boolean): string | null
Добавил значения по умолчанию в в `crypto.md `

2024-02-27 10:16 UTC, MrSheriff commented
> Всё ещё нет `scripts.om.d.ts`

Добавил

2024-02-27 14:33 UTC, iMoonGoose requested changes

2024-02-27 14:33 UTC, iMoonGoose commented on API/crypto.md
> +hash(algo: string , data: string , binary?: boolean): string | null
Мой косяк, забыл что в `.d.ts` нельзя указывать состояние по умолчанию

2024-02-27 14:33 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary` выставлено в `true`, то хэш возвращается в виде бинарных данных.<br>
Так как он выглядит? Я понимаю, как выглядит base64, я понимаю, как выглядит шестнадцетиричные цифры строкой, а тут что? Как читателю понять, что он получит? Идти учить PHP?

2024-02-27 14:33 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary` выставлено в `true`, то хэш возвращается в виде бинарных данных.<br>
Это тот же вид бинарных данныъ, что в `hmac`?

2024-02-27 14:33 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary` выставлено в `true`, то hmac возвращается в виде бинарных данных, закодированных с помощью Base64 в формате "==Base64String==".<br>
1. Каких требований? HMAC по своему определению возвращает байты. base64 - это байты (закодированные в текст), то что оно сейчас возвращает — это не байты (не соответствует base64). Как человек, читающий документацию, должен понять, почему функция называется hmac, но возвращает не то, что должна возвращать hmac? Почему заказчик не может добавить лишние 4 строки кода и самостоятельно обернуть base64 в `==%base64%==`? Тогда проблема 2 уйдет сама собой

2. Не устраивает тем, что `=` является частью кодировки `base64`. Если я увижу `A5asdsa=%` я сразу пойму, что
- это не base64
- скопировано неверно
Если я увижу `A5asdsa==` мне как понимать, это мне вырезали только base64 или кто-то лишнее равно ошибочно скопировал?

В общем, я не понимаю, почему такая реализация. Ответ "потому что заказчику надо" не годится. А другому заказчику будет надо по-другому, сделаем функцию hmac2? Добавим второй опциональный аргумент? Это общий функционал, namespace называется `crypto`, а не `sbebankPoprosil`

2024-02-27 15:26 UTC, MrSheriff commented on API/crypto.md
> +Если `binary` выставлено в `true`, то хэш возвращается в виде бинарных данных.<br>
> Как читателю понять, что он получит?

Ну если читатель не знает для чего hash_hmac - то только изучать, да.

Например, это будет нужно для получения нечто подобного
```
HMAC-SHA256(HMAC-SHA256(HMAC-SHA256(HMAC-SHA256("AWS4" + "<YourSecretAccessKey>","20130524"),"us-east-1"),"s3"),"aws4_request")						
```
для аутенфикации на AWS S3
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

Бинарные данные - это когда хэш возвращается as is, а не превращается в данные в шестнадцатеричной кодировке.

2024-02-27 15:35 UTC, MrSheriff commented on API/crypto.md
> +Если `binary` выставлено в `true`, то hmac возвращается в виде бинарных данных, закодированных с помощью Base64 в формате "==Base64String==".<br>
> Почему заказчик не может добавить лишние 4 строки кода

Потому что происходит передача данных между двумя совершенно разными системами: JS и PHP.
Если бы всё было просто, то ничего бы не понадобилось.
Но при передаче бинарных данных происходит нарушение целостности данных, поэтому происходит кодирование бинарных данных в base64.
Чтобы понять, что это именно мы закодировали бинарные данные в base64, добавляются по два символа в начало и в конец.

> Не устраивает тем, что = является частью кодировки base64

Не обязательно. Например, `3veR5tQ7` прекрасно декодируется - это тоже валидный Base64
И именно потому, что `=` уже может присутствовать, выбран `=` для оборачивания.
Как раз, чтобы не плодить сущности.

> А другому заказчику будет надо по-другому, сделаем функцию hmac2? Добавим второй опциональный аргумент?

Пока это получилось универсальным решением.
Будет необходимо что-то другое - появится другое.

2024-02-28 04:50 UTC, iMoonGoose requested changes

2024-02-28 04:50 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary` выставлено в `true`, то hmac возвращается в виде бинарных данных, закодированных с помощью Base64 в формате "==Base64String==".<br>
То есть, если исходный ключ будет `==aaaaa==`, то функция неверно его воспримет как base64 `aaaaa`? Может добавить параметр `keyFormat: "utf-8" | "base64" | "hexits"`?

2024-02-28 04:50 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary` выставлено в `true`, то хэш возвращается в виде бинарных данных.<br>
Строка — это не бинарные данные, а текстовые. Что я получу, если я введу 
```
const binaryHash = om.crypto.hash(
    "sha1",
    "data",
    true
);

console.log(typeof binaryHash);
console.log(binaryHash );
```
?

2024-02-28 05:51 UTC, MrSheriff commented on API/crypto.md
> +Если `binary` выставлено в `true`, то хэш возвращается в виде бинарных данных.<br>
Получишь набор странных символов.

2024-02-28 05:52 UTC, MrSheriff commented on API/crypto.md
> +Если `binary` выставлено в `true`, то hmac возвращается в виде бинарных данных, закодированных с помощью Base64 в формате "==Base64String==".<br>
Поскольку `aaaaa` невалидное base64, то ничего не произойдёт. Будет использованно `==aaaaa==` as is.

2024-02-28 16:44 UTC, iMoonGoose approved these changes

2024-02-29 09:36 UTC, kolyan-r approved these changes

2024-03-13 15:41 UTC, m-golovkina requested changes

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +Метод для получения хэша строки `data` (переданной в кодировке `UTF-8`) по указанному в алгоритму `algo`. Полный список доступных алгоритмов может быть получен с помощью метода `getHashAlgorithms()`.
Лишний предлог `в`: ...по указанному алгоритму `algo`

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +Если `binary = true`, то хэш возвращается в виде бинарных данных инкапсулированных в специальный объект [`BinaryData`](#binarydata).
Нужна запятая: ...в виде бинарных данных`,` инкапсулированных в специальный объект

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +Метод для получения подписи [`HMAC (Hash-based Message Authentication Code)`](https://ru.wikipedia.org/wiki/HMAC) для строки `data` (переданной в кодировке `UTF-8`) с использованием ключа `key`и алго
Не хватает пробела после `key`

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +Ключ `key` может быть передан в виде строки в кодировке `UTF-8` или в бинарном виде инкапсулированным в объект [`BinaryData`](#binarydata). Аналогично `hash`, полный список доступных алгоритмов хэшир
1) Нужна запятая: ...в бинарном виде`,` инкапсулированным в объект
2) Поправить начало второго предложения: Аналогично методу `hash()`, ...
Или вообще убрать эту часть

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +Если `binary = true`, то хэш возвращается в виде бинарных данных инкапсулированных в специальный объект [`BinaryData`](#binarydata).
Опять же нужна запятая после слова `данных`

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +Пример использования для получения подписи сервисы [`AWS s3`](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html):
Не пойму вот это `подписи сервисы`.  Тут знаков препинания не хватает или склонение неверное `подписи сервиса`?

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +const signature = om.crypto.hmac('sha-256', stringToSign, signingKey);
Не вижу определения `stringToSign`. Наверно лучше тоже обозначить строкой
```
const signature = om.crypto.hmac('sha-256', 'stringToSign', signingKey);
```

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +Возвращает список алгоритмов хэширования, которые могут быть использованы в параметре `algo` метода `hash`.
В описании название метода лучше писать со скобками: ...в параметре `algo` метода `hash()`.

2024-03-13 15:41 UTC, m-golovkina commented on API/crypto.md
> +Возвращает список алгоритмов хэширования, которые могут быть использованы в параметре `algo` метода `hmac`.
В описании название метода лучше писать со скобками: ...в параметре `algo` метода `hmac()`.

2024-03-13 15:48 UTC, iMoonGoose commented on API/crypto.md
> +Метод для получения хэша строки `data` (переданной в кодировке `UTF-8`) по указанному в алгоритму `algo`. Полный список доступных алгоритмов может быть получен с помощью метода `getHashAlgorithms()`.
Сделано

2024-03-13 15:48 UTC, iMoonGoose commented on API/crypto.md
> +Метод для получения подписи [`HMAC (Hash-based Message Authentication Code)`](https://ru.wikipedia.org/wiki/HMAC) для строки `data` (переданной в кодировке `UTF-8`) с использованием ключа `key`и алго
сделано

2024-03-13 15:49 UTC, iMoonGoose commented on API/crypto.md
> +Ключ `key` может быть передан в виде строки в кодировке `UTF-8` или в бинарном виде инкапсулированным в объект [`BinaryData`](#binarydata). Аналогично `hash`, полный список доступных алгоритмов хэшир
1. тут тире скорее
2. поправил

2024-03-13 15:50 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary = true`, то хэш возвращается в виде бинарных данных инкапсулированных в специальный объект [`BinaryData`](#binarydata).
Поправил

2024-03-13 15:51 UTC, iMoonGoose commented on API/crypto.md
> +Пример использования для получения подписи сервисы [`AWS s3`](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html):
Переписал

2024-03-13 15:52 UTC, iMoonGoose commented on API/crypto.md
> +const signature = om.crypto.hmac('sha-256', stringToSign, signingKey);
Поправил

2024-03-13 15:52 UTC, iMoonGoose commented on API/crypto.md
> +Возвращает список алгоритмов хэширования, которые могут быть использованы в параметре `algo` метода `hash`.
Поправил

2024-03-13 15:52 UTC, iMoonGoose commented on API/crypto.md
> +Возвращает список алгоритмов хэширования, которые могут быть использованы в параметре `algo` метода `hmac`.
Поправил

2024-03-13 16:39 UTC, iMoonGoose commented on API/crypto.md
> +Если `binary = true`, то хэш возвращается в виде бинарных данных инкапсулированных в специальный объект [`BinaryData`](#binarydata).
Поправил

2024-03-14 06:44 UTC, merged