Центр web-уведомлений Web Notice Center
optimacros/scripts_documentation pull request #82
Opened 2024-05-11 21:29 UTC by iMoonGoose

https://rucom.optimacros.com/topic/18378/epic-mw-центр-web-уведомлений-web-notice-center-пользователей-воркспейса-и-модели

2024-05-14 17:39 UTC, m-golovkina requested changes

2024-05-15 08:11 UTC, iMoonGoose commented on API/notifications.md
> +◾️ `'%ALL_MODELLERS%'` - пользователи, у которых есть привилегии `modeller`
У роли `admin` несколько привелегий: выдавать другим пользователям роли моделер и админ, упарвлять воркспейсом через панель администратора и т.д.

2024-05-15 08:18 UTC, iMoonGoose commented on API/notifications.md
> +Устанавливает адресата или адресатов. В качестве идетнификатора адресата используется `e-mail` пользователей, который использовался им для регистрации в системе в Login Centre, или — для упрощения ра
Поправил

2024-05-15 08:19 UTC, iMoonGoose commented on API/connectors.md
> +```
Попрпаивил

2024-05-15 13:11 UTC, m-golovkina approved these changes

2024-05-16 05:28 UTC, merged