54786 use semicolon luke
optimacros/scripts_documentation pull request #83
Opened 2024-05-17 13:15 UTC by qx87

https://rucom.optimacros.com/topic/55194

2024-05-20 19:32 UTC, m-golovkina commented on API/scripts.om.d.ts
> +	[key: string]: string[];
Почему поменял 4 пробела на таб в этом файле ts? Мы же договарились что пишем код с правилом отступа в 4 пробела. У меня даже в VSCode кнопка таб настроена ставить 4 пробела. Не помню точно с чем это было связано. Надо у Димы уточнить на дейли. Вроде из-за того что таб может выглядеть по разному в разных системах при чтении кода. И если в одном коде разные разработчики будут ставить разные отступы, то выглядеть это будет по ужасно (свястопляски). Например тут в гитлаб как видишь таб выглядит шире в два раза. А пробел - он везде пробел одинаков.

2024-05-20 20:02 UTC, m-golovkina commented on API/scripts.om.d.ts
>  export interface StorageExporter extends Exporter {
В документации в этом интерфейсе еще есть методы
```
setFormat(format: string): this;
setDelimiter(delimiter: string): this;
```
Они так же есть в `Exporter`, но тут они видимо перегружены и наверно тоже надо их сюда добавить.

2024-05-20 20:07 UTC, m-golovkina commented on API/scripts.om.d.ts
> +	open(name: string): MulticubeTab | undefined;
Тут ведь удаляем `undefined` ?? в документации ты вроде удалил

2024-05-20 20:16 UTC, m-golovkina commented on API/scripts.om.d.ts
> +	copyVersion(from: string, to: string): Object;
А давай спросим у MW какой там точно объект возвращается и опишем его тип в декларации. Вроде такой ```ts
{
    success: boolean;
}
```

2024-05-20 20:26 UTC, m-golovkina commented on API/scripts.om.d.ts
> +	getReportFilePath(): string | undefined;
В документации указан тип `string | null`

2024-05-20 20:38 UTC, m-golovkina commented on API/scripts.om.d.ts
> +	makeCodeExecutionAction(code: string): CodeExecutionAction;Zz
`Zz...` Смешно )) Я удалю

2024-05-21 12:06 UTC, m-golovkina commented on API/scripts.om.d.ts
> +	dateFilter(beginAt?: string | number | undefined | null, endAt?:  string | number | undefined | null): this;
Как то странно описаны входные параметры. И знаком вопроса помечены как опциональные и еще `undefined` добавили. Вот так вполне достаточно 
```ts
dateFilter(beginAt?: string | number | null, endAt?:  string | number | null): this;
```

2024-05-22 19:25 UTC, qx87 commented on API/scripts.om.d.ts
> +	run(name: string): { success: boolean, error: undefined | string };
Исправил

2024-05-22 19:25 UTC, qx87 commented on API/scripts.om.d.ts
> +	dateFilter(beginAt?: string | number | undefined | null, endAt?:  string | number | undefined | null): this;
Исправил

2024-06-11 08:39 UTC, qx87 commented on API/scripts.om.d.ts
> +	open(name: string): MulticubeTab | undefined;
Удалили.

2024-06-11 08:41 UTC, qx87 commented on API/scripts.om.d.ts
> +	getReportFilePath(): string | undefined;
Оставил `getReportFilePath(): string;`. Данила ошибся: здесь не возвращается `null`, здесь бросается исключение.

2024-06-14 18:08 UTC, m-golovkina requested changes

2024-06-17 05:51 UTC, qx87 commented on API/scripts.om.d.ts
> +		ObjectId(id?: string): Types.ObjectId;
Да, сознательно. Этот вопрос мы обсуждали с Данилом.

2024-06-17 05:52 UTC, qx87 commented on API/scripts.om.d.ts
> -	 */
Если считаешь важным -- ок, возвращай.

2024-06-17 05:52 UTC, qx87 commented on API/exportImport.md
>  Устанавливает кодировку. По умолчанию: `'UTF-8'`.
Хорошее замечание. Спросил у Данила.

2024-06-17 05:54 UTC, qx87 commented on API/common.md
> +Возвращает массив сущностей [`EntityInfo`](./views.md#entity-info) по массиву их [`longId`](./views.md#long-id). Корректно работает, только если все переданные `longId` корректные. Использовать с ост
Я не стал распространяться, потому что ты зарепортила этот баг, я его передал в mw, и мы надеемся наскорейшее разрешение. (Понимаю, что немного смешно) Но если хочешь -- допиши.

2024-06-17 07:46 UTC, qx87 commented on API/exportImport.md
>  Устанавливает кодировку. По умолчанию: `'UTF-8'`.
В итоге убрал её вообще. (Потому что нафик она нужна ;-) )
В процессе работы над текущей веткой в main уже слили Importer.setEncoding(), поэтому это описание стало вообще не нужным. Режимы те же.

2024-06-17 14:30 UTC, m-golovkina approved these changes

2024-06-17 14:35 UTC, merged