API service description
optimacros/scripts_documentation pull request #9
Opened 2022-06-08 08:03 UTC by m-golovkina

2022-06-08 12:56 UTC, iMoonGoose requested changes
Отлично! Спасибо за руаботу! У меня тут только пара мелких пожеланий. Нужно, правда, чтобы Коля проверил на фактическую верность

2022-06-10 10:22 UTC, m-golovkina commented on API/apiService.md
> +Позволяет передать файл. В функцию передается индентификатор файла `fileId`, зарегистрированного в [`глобальном реестре`](../appendix/glossary.md#globalFileRegistry).
Добавила

2022-06-10 10:23 UTC, m-golovkina commented on API/apiService.md
> +append(name: string, value: unknown): this
Исправила. Только на number | string | bool | object
Массив -это же тоже тип object.

2022-06-17 09:36 UTC, iMoonGoose requested changes

2022-06-17 09:36 UTC, iMoonGoose commented on API/cubeCell.md
> +Устанавливает максимальное количесво выбранных клеток.
Добавь, пожалуйста, что без указания лимит будет 500 000. Верхяя граница формально отсутствует, но выше примерно 2 500 000 у меня вылетела ошибка `Error occurred during parsing: Unexpected EOF inside int64 field. `, поэтому большие кубы лучше перебирать чанками

2022-06-17 10:49 UTC, m-golovkina commented on API/cubeCell.md
> +Устанавливает максимальное количесво выбранных клеток.
Исправлено

2022-06-17 10:51 UTC, iMoonGoose approved these changes

2022-06-17 10:51 UTC, merged