67478 vertica connection
optimacros/scripts_documentation pull request #91
Opened 2024-09-12 08:50 UTC by johnrembo

https://rucom.optimacros.com/topic/67478

2024-09-12 12:20 UTC, iMoonGoose commented on API/relationalDB.md
> +loadImportBuilder(): PostgresqlImportBuilder;
Этот метод есть и в `PostgresqlConnectorBuilder`. В чём смысл дублирования? К тому же он не указан 
<img width="340" alt="image" src="https://github.com/user-attachments/assets/b49a4f95-3599-40cb-9fb2-86dc51451589">

2024-09-12 12:20 UTC, iMoonGoose commented on API/relationalDB.md
> +[`Коннектор`](../appendix/glossary.md#connector) для подключения к базе данных [`Vertica`](https://en.wikipedia.org/wiki/Vertica). Интерфейс наследуется от [`PostgresqlConnectorBuilder`](#postgresql-
Если он наследуется, то есть между ними какая-то прямая связь? Потому что в `PostgresqlConnectorBuilder` только один дополнительный метод и он специфичен для протокола Postgres. Используется протокол Postgres и его драйвер? Ограничения на совместимость?

2024-09-12 14:12 UTC, johnrembo commented on API/relationalDB.md
> +loadImportBuilder(): PostgresqlImportBuilder;
исправлено

2024-09-12 14:12 UTC, johnrembo commented on API/relationalDB.md
> +[`Коннектор`](../appendix/glossary.md#connector) для подключения к базе данных [`Vertica`](https://en.wikipedia.org/wiki/Vertica). Интерфейс наследуется от [`PostgresqlConnectorBuilder`](#postgresql-
да, используется драйвер pgsql. обнаруженные отличия на данный момент описаны в задаче https://rucom.optimacros.com/topic/67478

2024-09-12 18:50 UTC, iMoonGoose requested changes

2024-09-12 18:50 UTC, iMoonGoose commented on API/relationalDB.md
> +[`Коннектор`](../appendix/glossary.md#connector) для подключения к базе данных [`Vertica`](https://en.wikipedia.org/wiki/Vertica). Интерфейс наследуется от [`PostgresqlConnectorBuilder`](#postgresql-
Там не ограничения, там особенности работы с БД через коннектор postgres. Ок, пока неизвестно, значит

2024-09-12 18:50 UTC, iMoonGoose commented on API/scripts.om.d.ts
> +export interface VerticaConnectorBuilder extends PostgresqlConnectorBuilder {
Так как у Vertica есть родной драйвер, а такой тип подключения не основной, стоит отметить это в названии интерфейса `PgsqlDrivenVerticaConnectorBuilder`

2024-09-12 18:50 UTC, iMoonGoose commented on API/scripts.om.d.ts
> +	vertica(): VerticaConnectorBuilder;
Так как у Vertica есть родной драйвер, а такой тип подключения не основной, стоит отметить это в названии метода `verticaViaPgsqlDriver()`

2024-09-13 01:20 UTC, johnrembo commented on API/scripts.om.d.ts
> +export interface VerticaConnectorBuilder extends PostgresqlConnectorBuilder {
исправлено

2024-09-13 01:20 UTC, johnrembo commented on API/scripts.om.d.ts
> +	vertica(): VerticaConnectorBuilder;
исправлено

2024-09-25 16:43 UTC, m-golovkina commented on API/connectors.md
> +Возвращает коннектор [`PgsqlDrivenVerticaConnectorBuilder`](./relationalDB.md#vertica-connector-builder) для подключения к базе данных [`Vertica`](https://docs.vertica.com/).
Здесь указана ссылка на сайт документации Vertica. В файле `relationalDB.md` указана ссылка на **википедию**. Давайте определимся куда мы даем ссылку? Как я вижу для всех остальных БД указана ссылка на **википедию** везде. Только для `Snowflake` почему-то на `habr`

2024-09-26 11:09 UTC, merged